sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack --no-terminal --install-ghc build --fast --only-dependencies
- stack exec milkshake -- sitemap.yaml -c
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
deploy:
  provider: s3
  access_key_id: AKIAJYFERLPRLHF6R2AQ
  secret_access_key:
    secure: LxBvukC/KXEmcN0S6Ma6aSQrft1BO0EbtdedPghVdo1tJSbVn+BNbYtRrXIrz4nrY7YxdrjQevukkh9sXFzq/YY4ZrmlFp1JCtP2cGRWjGInZdjc85BGVcGb/1ASUfL1Bmi0r8EFy3CNZY1RA3ITAd1MJzsq0q4DQU0uOBl6sOM=
  bucket: ashley-allred.com
  local-dir: build/site
  acl: public_read
  region: us-west-1
  skip_cleanup: true
  on:
    repo: schell/ashley-allred
